version: '3.6'
services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: ddev-${DDEV_SITENAME}-crowdsec
    hostname: ${DDEV_SITENAME}-crowdsec
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - ".:/mnt/ddev_config"
    environment:
      - DISABLE_AGENT=true
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8080:8080
    ports:
      - "8080"
  web:
    links:
      - crowdsec:crowdsec
    volumes:
      - ../my-own-modules/crowdsec-bouncer:/var/www/html/wp-content/plugins/cs-wordpress-bouncer
