common:
  daemonize: false
  pid_dir: /var/run/
  log_media: file
  log_level: info
  log_dir: /var/log/
  working_dir: .
api:
  server:
    tls:
      cert_file: /tmp/cfssl/server.pem #Server side cert
      key_file: /tmp/cfssl/server-key.pem #Server side key
      ca_cert_path: /tmp/cfssl/ca-chain.pem #CA used to verify the client certs
      bouncers_allowed_ou:
        - bouncer-ou
      agents_allowed_ou:
        - agent-ou
