name: After Release

on:
  release:
    types: [published]

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display versions
      run: |
          echo "This is a test"
          echo ${{ github.event.release.upload_url }} 
          echo ${{ github.event.release.tag_name }}
