name: Release
# example: gh workflow run release.yml -f tag_name=v1.1.4 -f draft=true
on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      tag_name:
        type: string
        required: true
      draft:
        type: boolean
        description: Draft release
        default: false
      prerelease:
        type: boolean
        description: Prerelease
        default: false

permissions:
  contents: write

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Check naming convention
        run: |
          VERIF=$(echo ${{ github.event.inputs.tag_name }} | grep -E "^v([0-9]{1,}\.)([0-9]{1,}\.)([0-9]{1,})(-(alpha|beta)\.[0-9]{1,})?$")
          if [ ! ${VERIF} ]
          then
            echo "Tag name '${{ github.event.inputs.tag_name }}' does not comply with naming convention vX.Y.Z"
            exit 1
          fi

      - name: Set version number without v
        run: |
          echo "VERSION_NUMBER=$(echo ${{ github.event.inputs.tag_name }} | sed 's/v//g' )" >> $GITHUB_ENV

      - name: Clone sources
        uses: actions/checkout@v3

      - name: Check version ${{ env.VERSION_NUMBER }} consistency in CHANGELOG
        run: |
          # Check top ## [VERSION_NUMBER](GITHUB_URL/releases/tag/vVERSION_NUMBER) - yyyy-mm-dd in CHANGELOG.md
          CURRENT_DATE=$(date +'%Y-%m-%d')
          echo $CURRENT_DATE
          CHANGELOG_VERSION=$(grep -o -E "## \[(.*)\].* - $CURRENT_DATE"  CHANGELOG.md | head -1 | sed 's/ //g')
          echo $CHANGELOG_VERSION
          if [[ $CHANGELOG_VERSION == "##[${{ env.VERSION_NUMBER }}]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/tag/v${{ env.VERSION_NUMBER }})-$CURRENT_DATE" ]]
          then
              echo "CHANGELOG VERSION OK"
          else
              echo "CHANGELOG VERSION KO"
              exit 1
          fi
          
          # Check top [_Compare with previous release_](GITHUB_URL/compare/vLAST_TAG...vVERSION_NUMBER) in CHANGELOG.md
          echo "VERSION COMPARISON START"
          COMPARISON=$(grep -oP "\/compare\/\K(.*)$" CHANGELOG.md | head -1)
          LAST_TAG=$(curl -Ls -o /dev/null -w %{url_effective} $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/latest | grep -oP "\/tag\/\K(.*)$")
          if [[ $COMPARISON == "$LAST_TAG...v${{ env.VERSION_NUMBER }})" ]]
          then
            echo "VERSION COMPARISON OK"
          else
            echo "VERSION COMPARISON KO"
            echo $COMPARISON
            echo "$LAST_TAG...v${{ env.VERSION_NUMBER }})"
            exit 1
          fi

      - name: Check DDEV expected version in README and installation.yml
        run: |
          EXPECTED_VERSION=$(cat homeadditions/DDEV_EXPECTED_VERSION.txt)
          README_VERSION_1=$(grep -oP "This project is fully compatible with DDEV \K(.*)," README.md | sed 's/,//g')
          if [[ $README_VERSION_1 == $EXPECTED_VERSION ]]
          then
              echo "README VERSION 1 OK"
          else
              echo "README VERSION 1 KO"
              echo $README_VERSION_1
              echo $EXPECTED_VERSION
              exit 1
          fi
          
          INSTALL_VERSION=$(grep -oP "DDEV_VERSION: v\K(.*)$" .github/workflows/installation.yml)
          if [[ $INSTALL_VERSION == $EXPECTED_VERSION ]]
          then
              echo "INSTALL_VERSION OK"
          else
              echo "INSTALL_VERSION KO"
              echo $INSTALL_VERSION
              echo $EXPECTED_VERSION
              exit 1
          fi  

      - name: Create Tag ${{ github.event.inputs.tag_name }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ github.event.inputs.tag_name }}",
              sha: context.sha
            })

      - name: Prepare release notes
        run: |
          # Retrieve release body and remove ---
          VERSION_RELEASE_NOTES=$(awk -v ver="[${{ env.VERSION_NUMBER }}]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/tag/v${{ env.VERSION_NUMBER }})" '/^## / { if (p) { exit }; if ($2 == ver) { p=1; next} } p && NF' CHANGELOG.md | sed ':a;N;$!ba;s/\n---/ /g')
          echo "$VERSION_RELEASE_NOTES" >> CHANGELOG.txt

      - name: Create release ${{ env.VERSION_NUMBER }}
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.txt
          name: ${{ env.VERSION_NUMBER }}
          tag_name: ${{ github.event.inputs.tag_name }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}

  after-release:
    name: After release
    runs-on: ubuntu-latest
    if: success()
    needs: [create-release]

    steps:
      - name: Test
        run: |
          echo "test"

      - name: Test 2
        run: |
          echo "test 2"